const services = ['Debt review removals', 'Debt mediation', 'Judgement removals', 'Prescribed debt assessments', 'Credit report investigations', 'Reckless lending assessments'];

export default function Home() {
  return <main>
    <header className="site-header"><a className="brand" href="#top" aria-label="Pacific Connect home"><img src="/logo-lockup.png" alt="Pacific Connect" className="brand-lockup" /></a><a className="header-link" href="mailto:Info@pacificconnect.co.za">Email Pacific Connect <span aria-hidden="true">↗</span></a></header>
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">CLEAR GUIDANCE. PRACTICAL SUPPORT.</p><h1>Understand your options. Take the next step.</h1><p className="hero-lede">Pacific Connect helps you assess your debt and credit position, understand the available route, and move forward with clearer information.</p><a className="primary-button" href="mailto:Info@pacificconnect.co.za?subject=Pacific%20Connect%20assessment%20enquiry">Email for an assessment <span aria-hidden="true">↗</span></a><p className="microcopy">A simple first conversation by email. Your matter is assessed individually.</p></div><div className="hero-art" aria-hidden="true"><img src="/logo-suite-source.png" alt="" /><div className="hero-art-overlay" /><div className="hero-stamp"><span>PC</span><small>Clear next steps</small></div></div></section>
    <section className="trust-strip"><div><strong>One matter at a time.</strong><span>Case-by-case assessment</span></div><div><strong>Plain language.</strong><span>Practical support</span></div><div><strong>No false promises.</strong><span>Outcomes depend on circumstances</span></div></section>
    <section className="section services-section" id="services"><div className="section-heading"><p className="eyebrow">WHAT WE CAN HELP WITH</p><h2>A clearer route starts with the right assessment.</h2><p>Tell us what you are dealing with. Pacific Connect can assess the available service route and explain what information is needed to move forward.</p></div><div className="service-grid">{services.map((service, index) => <div className="service-card" key={service}><span>0{index + 1}</span><h3>{service}</h3><b aria-hidden="true">↗</b></div>)}</div></section>
    <section className="assessment-section"><div className="assessment-number"><span>UP TO</span><strong>60%</strong></div><div><p className="eyebrow">DEBT MEDIATION</p><h2>Possible repayment relief, assessed for your circumstances.</h2><p>Monthly debt repayments may be reduced by up to 60%, depending on your financial situation and the agreement reached with creditors.</p><p className="fine-print">This is not a service fee or a guaranteed result. A specific reduction or outcome cannot be guaranteed.</p></div></section>
    <section className="contact-section" id="contact"><div><p className="eyebrow">START WITH AN EMAIL</p><h2>Send a short outline of your situation.</h2><p>Use the form to prepare an email enquiry, or contact the team directly at <a href="mailto:Info@pacificconnect.co.za">Info@pacificconnect.co.za</a>.</p></div><form className="lead-form" action="mailto:Info@pacificconnect.co.za" method="post" encType="text/plain"><label htmlFor="name">Your name</label><input id="name" name="name" type="text" autoComplete="name" required /><label htmlFor="email">Your email address</label><input id="email" name="email" type="email" autoComplete="email" required /><label htmlFor="message">How can we help?</label><textarea id="message" name="message" rows={4} required /><button type="submit">Prepare email enquiry <span aria-hidden="true">↗</span></button></form></section>
    <footer className="site-footer"><span>Pacific Connect</span><span>Clear advice. Better choices. Brighter futures.</span></footer>
  </main>;
}



