const email = 'Info@pacificconnect.co.za';
const intakeHref = 'mailto:Info@pacificconnect.co.za?subject=Request%20for%20a%20confidential%20assessment&body=Hello%20Pacific%20Connect%2C%0A%0AI%20would%20like%20to%20enquire%20about%3A%0A%0ABrief%20description%20of%20my%20matter%3A%0A%0AThank%20you.';

const services = [
  ['01', 'Debt review removals', 'A route back to a clearer credit position.'],
  ['02', 'Debt mediation', 'Practical conversations with creditors.'],
  ['03', 'Judgement removals', 'Assess the record. Understand the route.'],
  ['04', 'Prescribed debt', 'Check whether older debt still applies.'],
  ['05', 'Credit investigations', 'Find the facts behind your credit report.'],
  ['06', 'Reckless lending', 'Review the circumstances behind lending.'],
];

export default function Home() {
  return <main>
    <header className="site-header"><a className="brand" href="#top" aria-label="Pacific Connect home"><img src="/logo-wordmark-transparent.png" alt="Pacific Connect" className="brand-lockup" /></a><nav><a href="#services">Services</a><a href="#contact">Start a conversation <span aria-hidden="true">↗</span></a></nav></header>
    <section className="hero" id="top"><div className="hero-copy"><p className="kicker">PACIFIC CONNECT / PRIVATE INTAKE</p><h1>Clarity is a <em>better</em> place to start.</h1><p className="hero-lede">Understand your debt and credit position. See the route in front of you. Take the next step with practical guidance.</p><a className="button button-light" href={intakeHref}>Email for an assessment <span aria-hidden="true">↗</span></a><p className="hero-note">One confidential first conversation. Every matter is assessed individually.</p></div><div className="hero-visual" aria-hidden="true"><div className="visual-grid" /><div className="visual-orbit orbit-one" /><div className="visual-orbit orbit-two" /><img src="/logo-mark-transparent.png" alt="" /><div className="visual-caption"><span>PC / 01</span><strong>Connected thinking.</strong></div></div><div className="hero-index">01 <span>of</span> 04</div></section>
    <section className="statement"><p className="kicker">THE PACIFIC APPROACH</p><h2>Less noise.<br /><span>More next steps.</span></h2><p>Debt and credit decisions are personal. We make the route easier to understand, so you can move forward with better information.</p></section>
    <section className="services section" id="services"><div className="section-intro"><p className="kicker">WHAT WE CAN HELP WITH</p><h2>Find the right<br /><i>route.</i></h2><p>Start with a short outline. We will assess which service may fit your circumstances and explain what comes next.</p></div><div className="service-grid">{services.map(([number, title, copy]) => <article className="service-card" key={number}><span className="service-number">{number}</span><h3>{title}</h3><p>{copy}</p><span className="service-arrow" aria-hidden="true">↗</span></article>)}</div></section>
    <section className="process section"><div className="process-heading"><p className="kicker">HOW IT STARTS</p><h2>A considered<br /><i>first move.</i></h2></div><div className="process-steps"><div><span>01</span><h3>Send a short outline.</h3><p>Tell us what you are dealing with, without sending sensitive documents in your first email.</p></div><div><span>02</span><h3>We assess the route.</h3><p>Your matter is reviewed individually and the relevant service path is explained plainly.</p></div><div><span>03</span><h3>You see the next step.</h3><p>Move forward with a clearer understanding of the information and action required.</p></div></div></section>
    <section className="relief"><div className="relief-number"><span>UP TO</span><strong>60%</strong></div><div><p className="kicker">DEBT MEDIATION</p><h2>Possible repayment relief, assessed for your circumstances.</h2><p>Monthly debt repayments may be reduced by up to 60%, depending on your financial situation and the agreement reached with creditors.</p><p className="fine-print">This is not a service fee or a guaranteed result. A specific reduction or outcome cannot be guaranteed.</p></div></section>
    <section className="contact section" id="contact"><div className="contact-copy"><p className="kicker">START WITH AN EMAIL</p><h2>Tell us where<br /><i>you are.</i></h2><p>Use the form to prepare an enquiry, or write directly to <a href={`mailto:${email}`}>{email}</a>.</p><p className="privacy-note">Please do not send identity numbers, banking details or full documents in your first email.</p></div><form className="lead-form" action={`mailto:${email}`} method="post" encType="text/plain"><label htmlFor="name">Your name</label><input id="name" name="name" type="text" autoComplete="name" required /><label htmlFor="email">Your email address</label><input id="email" name="email" type="email" autoComplete="email" required /><label htmlFor="message">How can we help?</label><textarea id="message" name="message" rows={5} required /><button className="button button-red" type="submit">Prepare email enquiry <span aria-hidden="true">↗</span></button></form></section>
    <footer className="site-footer"><img src="/logo-wordmark-transparent.png" alt="Pacific Connect" /><span>Clear advice. Better choices. Brighter futures.</span><a href="#top">Back to top ↑</a></footer>
  </main>;
}
